import { before, after, test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash, randomBytes } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
import { applyVlmPaidEntitlementLifecycleEvent, evaluateVlmPaidEntitlementLifecycleTransition,
  type VlmPaidEntitlementLifecycleEvent } from '../../lib/commerce/vlm-entitlement-lifecycle';
import { upsertVlmPaidEntitlementFromStripeSession, type VlmPaidEntitlementStatus } from '../../lib/commerce/vlm-entitlement-ledger';
import { getVlmCurrentSkuTruth } from '../../lib/commerce/vlm-current-sku-truth';
import type { runRegisteredServiceRoleRpc } from '../../lib/db/supabase-rpc-operation-registry';
import type Stripe from 'stripe';

// Real PostgreSQL SQL execution in PGlite, not a fake receipt. The typed RPC
// adapter bypasses HTTP/GoTrue deliberately. Native multi-connection PG17 tests
// are separate: this suite makes no concurrency, real-payment or JWT claim.
const db = new PGlite();
const sql = readFileSync(new URL('./entitlement-store.sql', import.meta.url), 'utf8');
const saved = {url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY};
const hash = (s:string) => createHash('sha256').update(s).digest('hex');
before(async()=>{
  process.env.SUPABASE_URL='https://q4-no-network.invalid';
  process.env.SUPABASE_SERVICE_ROLE_KEY=randomBytes(24).toString('hex');
  await db.exec(readFileSync(new URL('./bootstrap-roles.sql', import.meta.url),'utf8'));
  await db.exec("SET velmere.disposable_entitlement_store='ISOLATED_TEST_ONLY'");
  await db.exec(sql);
});
after(async()=>{
  await db.close();
  for(const [key,value] of [['SUPABASE_URL',saved.url],['SUPABASE_SERVICE_ROLE_KEY',saved.key]]) {
    if(value===undefined)delete process.env[key!];else process.env[key!]=value;
  }
});
async function asRole<T>(role:string, query:string, params:unknown[]=[]):Promise<T[]> {
  assert.ok(['service_role','anon','authenticated'].includes(role));
  await db.exec(`SET ROLE ${role}`);
  try { return (await db.query<T>(query,params)).rows; } finally { await db.exec('RESET ROLE'); }
}
const created = '2026-01-01T00:00:00Z', expiry = '2099-01-01T00:00:00Z';
function record(id:string): Record<string,unknown> {
  return {p_id:id,p_stripe_session_id:'cs_test_'+id,p_stripe_customer_id:null,p_product_id:'vlm_pro_analysis_single',
    p_access_scope:'vlm_pro_analysis',p_context_hash:hash('context:'+id),
    p_context:{surface:'shield',locale:'en',depth:'pro',accountIdHash:hash('account:'+id)},p_locale:'en',
    p_amount_total:1000,p_currency:'EUR',p_customer_email:null,p_customer_name:null,p_payment_status:'paid',
    p_source:'stripe_webhook',p_audit_queue_id:null,p_expires_at:expiry,p_created_at:created};
}
async function create(id:string,changes:Record<string,unknown>={}) {
  const args={...record(id),...changes};
  const keys=Object.keys(args);
  const rows=await asRole<{result:Record<string,unknown>}>('service_role',
    `SELECT public.velmere_create_or_read_vlm_paid_entitlement(${keys.map((k,i)=>`${k} => $${i+1}`).join(',')}) AS result`,
    Object.values(args));
  return rows[0].result;
}
const rpc:typeof runRegisteredServiceRoleRpc=async input=>{
  assert.equal(input.operation,'vlm_paid_entitlement_lifecycle_apply');
  const args=input.args as Record<string,unknown>,keys=Object.keys(args);
  const rows=await asRole<{result:unknown}>('service_role',
    `SELECT public.velmere_apply_vlm_paid_entitlement_lifecycle_event(${keys.map((k,i)=>`${k} => $${i+1}`).join(',')}) AS result`,Object.values(args));
  return {data:rows[0].result,receipt:{schemaVersion:'velmere.bounded-rpc-receipt.v1',operation:input.operation,
    capability:'service_role_write',durationMs:0,deadlineMs:5000,aborted:false,durableBoundary:'service_role'}};
};
async function apply(id:string,event:VlmPaidEntitlementLifecycleEvent,eventId='evt:'+id+':'+event,sourceEventId='source:'+id) {
  return applyVlmPaidEntitlementLifecycleEvent({entitlementId:id,eventId,event,sourceEventId,dependencies:{rpc}});
}
async function state(id:string){return (await db.query<{status:string;expires_at:string}>(
  'SELECT status, expires_at::text FROM public.velmere_vlm_paid_entitlements WHERE id=$1',[id])).rows[0];}
async function countEvents(id:string){return Number((await db.query<{n:number}>(
  'SELECT count(*)::int AS n FROM velmere_billing_private.lifecycle_events WHERE entitlement_id=$1',[id])).rows[0].n);}

// Independent fixed policy table, not labels generated by either implementation.
const statuses:VlmPaidEntitlementStatus[]=['paid','active','expired','refunded','revoked','consumed'];
const expected:Record<VlmPaidEntitlementLifecycleEvent, Array<VlmPaidEntitlementStatus|null>>={
  expire:['expired','expired','expired',null,null,null],
  refund:['refunded','refunded','refunded','refunded',null,null],
  chargeback:['revoked','revoked','revoked','revoked','revoked',null],
  manual_revoke:['revoked','revoked','revoked','revoked','revoked',null],
  restore:[null,'active','active',null,null,null],
};
for(const event of Object.keys(expected) as VlmPaidEntitlementLifecycleEvent[]) {
  statuses.forEach((status,i)=>test(`Q4 SQL and real parser: ${event} from ${status}`,async()=>{
    const id=`q4_${event}_${status}`;assert.equal((await create(id)).ok,true);
    // Privileged test fixture setup only; this is not payment evidence.
    await db.query('UPDATE public.velmere_vlm_paid_entitlements SET status=$1 WHERE id=$2',[status,id]);
    const before=await state(id), result=await apply(id,event),target=expected[event][i];
    assert.equal(evaluateVlmPaidEntitlementLifecycleTransition({currentStatus:status,event}).ok,target!==null);
    assert.equal(result.ok,target!==null);
    if(result.ok){assert.equal(result.nextStatus,target);assert.equal(result.previousStatus,status);
      assert.equal(result.entitlementIdHash,hash(id));assert.equal(result.eventIdHash,hash('evt:'+id+':'+event));}
    assert.equal((await state(id)).status,target??status);
    assert.equal((await state(id)).expires_at,before.expires_at,'Transitions never refresh TTL');
    assert.equal(await countEvents(id),target===null?0:1);
  }));
}
test('Q4 create replay preserves original TTL, queue, timestamps and ownership',async()=>{
  const first=await create('q4_replay');
  const second=await create('q4_replay',{p_expires_at:'2100-01-01T00:00:00Z',p_created_at:'2027-01-01T00:00:00Z',p_audit_queue_id:'new_queue'});
  assert.equal(first.created,true);assert.equal(second.created,false);assert.equal(second.idempotent,true);
  for(const key of ['expires_at','created_at','updated_at','context','audit_queue_id'])assert.deepEqual(second[key],first[key]);
});
test('Q4 same Checkout Session cannot change account or product binding',async()=>{
  const id='q4_binding';const original=await create(id);assert.equal(original.ok,true);
  const changed=await create(id,{p_context:{...record(id).p_context as object,accountIdHash:hash('other-account')}});
  assert.equal(changed.ok,false);assert.equal(changed.error,'entitlement_binding_conflict');
  const row=(await db.query<{context:unknown}>('SELECT context FROM public.velmere_vlm_paid_entitlements WHERE id=$1',[id])).rows[0];
  assert.deepEqual(row.context,record(id).p_context);
  assert.equal((await create(id,{p_product_id:'vlm_advanced_analysis_single',p_access_scope:'vlm_advanced_analysis'})).ok,false);
});
test('Q4 one id cannot be reused by a different session',async()=>{
  const id='q4_id_conflict';await create(id);const result=await create(id,{p_stripe_session_id:'cs_test_other'});
  assert.equal(result.error,'entitlement_identity_conflict');
});
test('Q4 refund replay after chargeback cannot reactivate or rewrite the receipt',async()=>{
  const id='q4_replay_revoked';await create(id);
  const first=await apply(id,'refund','refund-original');assert.equal(first.ok,true);
  assert.equal((await apply(id,'chargeback')).ok,true);
  const replay=await apply(id,'refund','refund-original');assert.equal(replay.ok,true);
  if(replay.ok){assert.equal(replay.idempotent,true);assert.equal(replay.nextStatus,'refunded');}
  assert.equal((await state(id)).status,'revoked');assert.equal(await countEvents(id),2);
});
test('Q4 event identity reuse with different payload or entitlement is rejected',async()=>{
  await create('q4_event_a');await create('q4_event_b');assert.equal((await apply('q4_event_a','refund','shared')).ok,true);
  for(const [id,event,source] of [['q4_event_a','chargeback','source:q4_event_a'],['q4_event_b','refund','source:q4_event_a'],['q4_event_a','refund','different-source']] as const){
    const result=await apply(id,event,'shared',source);assert.equal(result.ok,false);
    if(!result.ok)assert.equal(result.error,'lifecycle_event_identity_conflict');
  }
  assert.equal((await state('q4_event_b')).status,'active');
});
test('Q4 refund before grant stays retryable and succeeds after the grant exists',async()=>{
  const id='q4_early';const first=await apply(id,'refund');assert.equal(first.ok,false);
  if(!first.ok)assert.equal(first.retryable,true);assert.equal(await countEvents(id),0);
  await create(id);assert.equal((await apply(id,'refund')).ok,true);assert.equal(await countEvents(id),1);
});
test('Q4 stale checkout replay cannot resurrect refunded or revoked grants',async()=>{
  for(const event of ['refund','chargeback'] as const){const id='q4_terminal_'+event;await create(id);await apply(id,event);
    const replay=await create(id,{p_expires_at:'2100-01-01T00:00:00Z'});assert.equal(replay.ok,false);
    assert.equal(replay.error,'entitlement_terminal_state');}
});
test('Q4 failed event receipt insertion atomically rolls back status update',async()=>{
  const id='q4_rollback';await create(id);
  await db.exec("ALTER TABLE velmere_billing_private.lifecycle_events ADD CONSTRAINT q4_injected_failure CHECK (entitlement_id <> 'q4_rollback')");
  const result=await apply(id,'refund');assert.equal(result.ok,false);if(!result.ok)assert.equal(result.retryable,true);
  assert.equal((await state(id)).status,'active');assert.equal(await countEvents(id),0);
  await db.exec('ALTER TABLE velmere_billing_private.lifecycle_events DROP CONSTRAINT q4_injected_failure');
  assert.equal((await apply(id,'refund')).ok,true);
});
for(const [label,change] of [
  ['missing owner',{p_context:{locale:'en'}}],['unpaid',{p_payment_status:'unpaid'}],
  ['demo receipt',{p_source:'local_demo_verify'}],['unknown product',{p_product_id:'not-a-product'}],
  ['wrong product scope',{p_access_scope:'vlm_advanced_analysis'}],['bad digest',{p_context_hash:'bad'}],
  ['wrong locale',{p_locale:'de'}],['expired creation',{p_expires_at:'2026-01-02T00:00:00Z'}],
] as const){test(`Q4 create refuses ${label} without a row`,async()=>{
  const id='q4_bad_'+label.replaceAll(' ','_');assert.equal((await create(id,change)).ok,false);assert.equal(await state(id),undefined);
});}
for(const role of ['anon','authenticated']){
  test(`Q4 ${role} cannot invoke lifecycle or read/write the ledger`,async()=>{
    await assert.rejects(()=>asRole(role,'SELECT * FROM public.velmere_vlm_paid_entitlements'),/permission denied/);
    await assert.rejects(()=>asRole(role,"UPDATE public.velmere_vlm_paid_entitlements SET status='active'"),/permission denied/);
    await assert.rejects(()=>asRole(role,"SELECT public.velmere_apply_vlm_paid_entitlement_lifecycle_event('none',$1,'refund',null,null,null,now())",[hash('none')]),/permission denied/);
  });
}
test('Q4 event journal denies update/delete even to service role',async()=>{
  await assert.rejects(()=>asRole('service_role',"DELETE FROM velmere_billing_private.lifecycle_events"),/permission denied/);
  await assert.rejects(()=>asRole('service_role',"UPDATE velmere_billing_private.lifecycle_events SET next_status='active'"),/permission denied/);
});
test('Q4 tables have FORCE RLS and functions retain SECURITY INVOKER with pinned search_path',async()=>{
  const policies=await db.query<{relrowsecurity:boolean;relforcerowsecurity:boolean}>("SELECT relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname IN ('velmere_vlm_paid_entitlements','lifecycle_events')");
  assert.equal(policies.rows.length,2);for(const row of policies.rows){assert.equal(row.relrowsecurity,true);assert.equal(row.relforcerowsecurity,true);}
  const funcs=await db.query<{prosecdef:boolean;proconfig:string[]}>("SELECT prosecdef,proconfig FROM pg_proc WHERE proname IN ('velmere_create_or_read_vlm_paid_entitlement','velmere_apply_vlm_paid_entitlement_lifecycle_event')");
  assert.equal(funcs.rows.length,2);for(const f of funcs.rows){assert.equal(f.prosecdef,false);assert.deepEqual(f.proconfig,['search_path=pg_catalog']);}
});
test('Q4 SQL requires explicit isolation acknowledgement and refuses reinstallation',async()=>{
  await db.exec('RESET velmere.disposable_entitlement_store');
  await assert.rejects(()=>db.exec(sql),/DISPOSABLE_STORE_ACK_REQUIRED/);await db.exec('ROLLBACK');
  await db.exec("SET velmere.disposable_entitlement_store='ISOLATED_TEST_ONLY'");
  await assert.rejects(()=>db.exec(sql),/EXISTING_BILLING_OBJECTS_REQUIRE_REVIEW/);await db.exec('ROLLBACK');
});
test('Q4 existing public sale containment remains unchanged',async()=>{
  for(const tier of ['pro','advanced'] as const){const truth=getVlmCurrentSkuTruth(tier,'en');assert.equal(truth.saleEnabled,false);assert.equal(truth.publicCheckoutAllowed,false);}
  const session: Stripe.Checkout.Session={
    adaptive_pricing:null,
    after_expiration:null,
    allow_promotion_codes:null,
    amount_subtotal:null,
    amount_total:null,
    billing_address_collection:null,
    cancel_url:null,
    client_reference_id:null,
    client_secret:null,
    collected_information:null,
    consent:null,
    consent_collection:null,
    currency:null,
    currency_conversion:null,
    customer:null,
    customer_account:null,
    customer_creation:null,
    customer_details:null,
    customer_email:null,
    discounts:null,
    integration_identifier:null,
    invoice:null,
    invoice_creation:null,
    locale:null,
    managed_payments:null,
    metadata:{kind:'vlm_paid_access',productId:'vlm_pro_analysis_single',locale:'en',surface:'shield',accountIdHash:hash('account')},
    origin_context:null,
    payment_intent:null,
    payment_link:null,
    payment_method_collection:null,
    payment_method_configuration_details:null,
    payment_method_options:null,
    permissions:null,
    recovered_from:null,
    saved_payment_method_options:null,
    setup_intent:null,
    shipping_address_collection:null,
    shipping_cost:null,
    status:null,
    submit_type:null,
    subscription:null,
    success_url:null,
    total_details:null,
    ui_mode:null,
    url:null,
    wallet_options:null,
    id:'cs_test_public_disabled',
    object:'checkout.session',
    created:0,
    expires_at:4070908800,
    livemode:false,
    mode:'payment',
    payment_status:'paid',
    custom_fields:[],
    payment_method_types:['card'],
    shipping_options:[],
    automatic_tax:{enabled:false,liability:null,provider:null,status:null},
    custom_text:{after_submit:null,shipping_address:null,submit:null,terms_of_service_acceptance:null},
  };
  const result=await upsertVlmPaidEntitlementFromStripeSession(session,'stripe_webhook');assert.equal(result.ok,false);
  if(!result.ok)assert.match(result.error,/checkout_disabled|not_for_sale/);
});
