import {after,before,test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import type {PGlite} from '@electric-sql/pglite';
import {database,create,hold,hash,rpc} from '../c15-q8/test-helpers';
import {parseBillingReconciliationReport,type BillingReconciliationReport,RECONCILIATION_CODES} from '../../lib/payments/billing-reconciliation-report';
const query=readFileSync(new URL('./reconcile.sql',import.meta.url),'utf8');
let db:PGlite;
before(async()=>{db=await database(true,true);});after(async()=>{await db.close();});
async function report():Promise<BillingReconciliationReport>{return parseBillingReconciliationReport((await db.query<{report:unknown}>(query)).rows[0].report);}
async function isolated(fn:()=>Promise<void>){await db.exec('BEGIN');try{await fn();}finally{await db.exec('ROLLBACK');}}
async function event(name:string){return rpc(db,'velmere_claim_stripe_webhook_event',{p_event_id:name,p_event_type:'charge.refunded',p_event_created_at:1700000000,p_stale_after_seconds:300});}
async function effect(name:string,key='vlm_paid_access:entitlement_terminal_revoke'){
 const token=randomUUID();await rpc(db,'velmere_claim_stripe_webhook_effect',{p_event_id:name,p_event_type:'charge.refunded',p_effect_key:key,p_requested_lease_token:token,p_stale_after_seconds:300});return token;
}
const has=(r:BillingReconciliationReport,code:keyof typeof RECONCILIATION_CODES)=>r.issues.some(i=>i.code===code);
const allTables=['public.velmere_vlm_paid_entitlements','velmere_billing_private.lifecycle_events','velmere_billing_private.session_terminal_holds','public.velmere_stripe_webhook_events','velmere_webhook_private.effects','velmere_payment_private.event_identities','velmere_payment_private.event_watermarks'];
async function snapshot(){const out:unknown[]=[];for(const name of allTables)out.push((await db.query(`SELECT row_to_json(t) AS row FROM ${name} t ORDER BY row_to_json(t)::text`)).rows);return out;}
test('Q9 empty stores are EMPTY, never a paid readiness pass',async()=>{const r=await report();assert.equal(r.verdict,'EMPTY');assert.equal(r.releaseApproved,false);assert.equal(r.issueCount,0);});
test('Q9 a legitimate active grant is consistent, not a payment certificate',async()=>isolated(async()=>{await create(db,'valid');const r=await report();assert.equal(r.verdict,'CONSISTENT_WITHIN_SCOPE');assert.equal(r.counts.entitlements,1);assert.equal(r.scope,'INTERNAL_DATABASE_CONSISTENCY_NOT_STRIPE_TRUTH');}));
test('Q9 terminal hold before grant is a legitimate state',async()=>isolated(async()=>{await hold(db,'early');assert.equal((await report()).issueCount,0);}));
test('Q9 successful terminal hold and lifecycle are consistent',async()=>isolated(async()=>{await create(db,'terminal');await hold(db,'terminal');const r=await report();assert.equal(r.issueCount,0);assert.equal(r.counts.lifecycleEvents,1);}));
test('Q9 detects active state under a terminal hold without performing repair',async()=>isolated(async()=>{await create(db,'corrupt');await hold(db,'corrupt');await db.exec("UPDATE public.velmere_vlm_paid_entitlements SET status='active' WHERE id='corrupt'");const before=await snapshot();const r=await report();assert.ok(has(r,'ACTIVE_GRANT_UNDER_TERMINAL_HOLD'));assert.equal(r.verdict,'REVIEW_REQUIRED');assert.deepEqual(await snapshot(),before);}));
test('Q9 detects hold context mismatch without exporting owner PII',async()=>isolated(async()=>{await create(db,'mismatch',{p_customer_email:'private-customer@example.invalid',p_customer_name:'Private Person'});await hold(db,'mismatch');await db.query('UPDATE public.velmere_vlm_paid_entitlements SET context_hash=$1 WHERE id=$2',[hash('changed'),'mismatch']);const r=await report();assert.ok(has(r,'HOLD_GRANT_BINDING_MISMATCH'));const text=JSON.stringify(r);for(const secret of ['private-customer@example.invalid','Private Person','cs_test_mismatch','evt_mismatch_refund',hash('owner:mismatch')])assert.equal(text.includes(secret),false);}));
test('Q9 detects mismatched watermark and durable event identity',async()=>isolated(async()=>{await rpc(db,'velmere_apply_payment_event_watermark',{p_subject_key:'stripe:object:fixture',p_event_id:'evt_identity',p_event_created_at:1700000000,p_event_kind:'refund',p_event_priority:80,p_terminal:true});await db.exec("UPDATE velmere_payment_private.event_identities SET subject_key='stripe:object:other' WHERE event_id='evt_identity'");assert.ok(has(await report(),'WATERMARK_IDENTITY_MISMATCH'));}));
test('Q9 detects mismatched effect type',async()=>isolated(async()=>{await event('evt_type');await effect('evt_type');await db.exec("UPDATE velmere_webhook_private.effects SET event_type='charge.dispute.created' WHERE event_id='evt_type'");assert.ok(has(await report(),'EFFECT_EVENT_TYPE_MISMATCH'));}));
test('Q9 active leases are not reported as expired',async()=>isolated(async()=>{await event('evt_live');await effect('evt_live');const r=await report();assert.equal(has(r,'EVENT_LEASE_EXPIRED'),false);assert.equal(has(r,'EFFECT_LEASE_EXPIRED'),false);assert.equal(r.issueCount,0);}));
test('Q9 expired event and effect leases are review signals, not executed retries',async()=>isolated(async()=>{await event('evt_old');await effect('evt_old');await db.exec("UPDATE public.velmere_stripe_webhook_events SET lease_expires_at=statement_timestamp()-interval '1 second'; UPDATE velmere_webhook_private.effects SET lease_expires_at=statement_timestamp()-interval '1 second'");const r=await report();assert.ok(has(r,'EVENT_LEASE_EXPIRED'));assert.ok(has(r,'EFFECT_LEASE_EXPIRED'));assert.equal(r.errorCount,0);}));
for(const status of ['retryable_failed','dead_letter'] as const)test(`Q9 ${status} queues are visible`,async()=>isolated(async()=>{await event('evt_queue');const token=await effect('evt_queue');await rpc(db,'velmere_complete_stripe_webhook_event',{p_event_id:'evt_queue',p_event_type:'charge.refunded',p_expected_attempt:1,p_status:status,p_error_code:'fixture_error'});await rpc(db,status==='dead_letter'?'velmere_dead_letter_stripe_webhook_effect':'velmere_fail_stripe_webhook_effect',{p_event_id:'evt_queue',p_effect_key:'vlm_paid_access:entitlement_terminal_revoke',p_expected_attempt:1,p_lease_token:token,p_error_code:'fixture_error'});const r=await report();assert.ok(has(r,status==='dead_letter'?'EVENT_DEAD_LETTER':'EVENT_RETRY_PENDING'));assert.ok(has(r,status==='dead_letter'?'EFFECT_DEAD_LETTER':'EFFECT_RETRY_PENDING'));}));
test('Q9 standalone legacy effect is a warning, not a proved broken payment',async()=>isolated(async()=>{await effect('evt_standalone');const r=await report();assert.ok(has(r,'EFFECT_WITHOUT_INBOX'));assert.equal(r.errorCount,0);}));
test('Q9 processed inbox with unfinished effect requires review',async()=>isolated(async()=>{await event('evt_mixed');await effect('evt_mixed');await rpc(db,'velmere_complete_stripe_webhook_event',{p_event_id:'evt_mixed',p_event_type:'charge.refunded',p_expected_attempt:1,p_status:'processed',p_error_code:null});assert.ok(has(await report(),'PROCESSED_EVENT_WITH_UNFINISHED_EFFECT'));}));
test('Q9 completed VLM revoke must have a durable lifecycle record',async()=>isolated(async()=>{await event('evt_missing_lifecycle');const token=await effect('evt_missing_lifecycle');await rpc(db,'velmere_complete_stripe_webhook_effect',{p_event_id:'evt_missing_lifecycle',p_effect_key:'vlm_paid_access:entitlement_terminal_revoke',p_expected_attempt:1,p_lease_token:token,p_result_json:{ok:true}});assert.ok(has(await report(),'COMPLETED_TERMINAL_EFFECT_WITHOUT_LIFECYCLE'));}));
test('Q9 unrelated completed effects do not imply missing VLM grants',async()=>isolated(async()=>{await event('evt_other');const token=await effect('evt_other','commerce:order_persistence');await rpc(db,'velmere_complete_stripe_webhook_effect',{p_event_id:'evt_other',p_effect_key:'commerce:order_persistence',p_expected_attempt:1,p_lease_token:token,p_result_json:{ok:true}});assert.equal((await report()).issueCount,0);}));
test('Q9 bounded samples retain the full issue count and explicit truncation',async()=>isolated(async()=>{await db.exec("INSERT INTO public.velmere_stripe_webhook_events(id,event_type,event_created_at,status,attempt_count,claimed_at,lease_expires_at,last_error_code) SELECT 'evt_bulk_'||g,'charge.refunded',1700000000,'dead_letter',1,statement_timestamp(),statement_timestamp(),'fixture' FROM generate_series(1,105) g");const r=await report();assert.equal(r.issueCount,105);assert.equal(r.issues.length,100);assert.equal(r.truncated,true);assert.equal(r.warningCount,105);}));
test('Q9 executes in a READ ONLY transaction',async()=>{await db.exec('BEGIN READ ONLY');try{assert.equal((await report()).readOnly,true);await assert.rejects(()=>db.exec("DELETE FROM public.velmere_stripe_webhook_events"),/read.only/i);}finally{await db.exec('ROLLBACK');}});
for(const role of ['anon','authenticated'])test(`Q9 ${role} cannot use the internal cross-account diagnostic`,async()=>{await db.exec(`BEGIN; SET LOCAL ROLE ${role}`);try{await assert.rejects(()=>report(),/permission denied/);}finally{await db.exec('ROLLBACK');}});
test('Q9 trusted service role can run the read-only scan',async()=>{await db.exec('BEGIN READ ONLY; SET LOCAL ROLE service_role');try{assert.equal((await report()).verdict,'EMPTY');}finally{await db.exec('ROLLBACK');}});
test('Q9 missing store is a database error, never an empty healthy result',async()=>isolated(async()=>{await db.exec('ALTER TABLE public.velmere_stripe_webhook_events RENAME TO temporarily_absent');await assert.rejects(()=>report(),/does not exist/);}));
const valid=():BillingReconciliationReport=>({schema:'velmere.billing-reconciliation.v1',scope:'INTERNAL_DATABASE_CONSISTENCY_NOT_STRIPE_TRUTH',observedAt:'2026-09-19T00:00:00.000Z',readOnly:true,releaseApproved:false,sampleLimit:100,counts:{entitlements:0,lifecycleEvents:0,effects:0,events:0,eventIdentities:0,watermarks:0,terminalHolds:0},issueCount:0,errorCount:0,warningCount:0,truncated:false,verdict:'EMPTY',issues:[]});
const invalid:Array<[string,(r:Record<string,unknown>)=>void]>= [
 ['release approval',r=>{r.releaseApproved=true;}],['false string',r=>{r.readOnly='true';}],['unknown field',r=>{r.secret='bad';}],['wrong scope',r=>{r.scope='STRIPE_VERIFIED';}],
 ['inconsistent counters',r=>{r.issueCount=1;}],['negative count',r=>{r.errorCount=-1;}],['fractional count',r=>{r.warningCount=.5;}],['wrong empty verdict',r=>{r.verdict='CONSISTENT_WITHIN_SCOPE';}],
 ['invalid date',r=>{r.observedAt='2026-02-31T00:00:00.000Z';}],['silent truncation',r=>{r.truncated=true;}],['changed sample limit',r=>{r.sampleLimit=200;}],['unknown counter',r=>{r.counts={...valid().counts,customers:0};}],
];
for(const [label,mutate] of invalid)test(`Q9 parser refuses ${label}`,()=>{const r:Record<string,unknown>=structuredClone(valid());mutate(r);assert.throws(()=>parseBillingReconciliationReport(r),/INVALID_RECONCILIATION_REPORT/);});
test('Q9 parser rejects outer arrays, null and missing fields',()=>{for(const value of [null,[],[valid()],{},undefined])assert.throws(()=>parseBillingReconciliationReport(value));});
test('Q9 parser refuses unknown, duplicated or misclassified issue entries',()=>{
 const r=valid();r.issueCount=1;r.errorCount=1;r.verdict='REVIEW_REQUIRED';r.issues=[{code:'ACTIVE_GRANT_UNDER_TERMINAL_HOLD',severity:'error',entity:'entitlement',fingerprint:hash('fixture')}];assert.equal(parseBillingReconciliationReport(r).issueCount,1);
 for(const change of [{code:'__proto__'},{severity:'warning'},{entity:'event'},{fingerprint:'raw-secret'},{token:'secret'}])assert.throws(()=>parseBillingReconciliationReport({...r,issues:[{...r.issues[0],...change}]}));
 assert.throws(()=>parseBillingReconciliationReport({...r,issueCount:2,errorCount:2,issues:[r.issues[0],r.issues[0]]}));
});
