import assert from "node:assert/strict";
import fs from "node:fs";
const route=fs.readFileSync("lib/server/lazy-route-modules/account--customer-artifact.ts","utf8");
const migration=fs.readFileSync("supabase/migrations/20260918024500_velmere_c14_historical_artifact_direct_read_boundary.sql","utf8");
const current=fs.readFileSync("lib/security/customer-report-request.ts","utf8");
const json=fs.readFileSync("app/api/audit/report/route.ts","utf8");
const pdf=fs.readFileSync("app/api/audit/report-pdf/route.ts","utf8");
const shield=fs.readFileSync("scripts/c13/shield-db-test.py","utf8");
const policy=JSON.parse(fs.readFileSync("config/c14-historical-artifact-access-policy.json","utf8"));
assert.match(route,/authorizeHistoricalCustomerArtifactAccess/);
assert.match(route,/resolveCustomerOwnedDataBoundary/);
assert.match(route,/client: undefined/);
assert.doesNotMatch(route,/getP85OwnerVisibleCustomerArtifact|listP85OwnerVisibleCustomerArtifacts|client: ownerClient/);
assert.match(route,/historical_artifact_current_entitlement_required/);
assert.match(route,/historical_paid_artifact_policy_undefined/);
assert.match(migration,/revoke select on table public\.velmere_customer_artifact_snapshots[\s\S]*authenticated/i);
assert.match(migration,/revoke select on table public\.velmere_customer_artifact_pdf_blobs[\s\S]*authenticated/i);
assert.match(migration,/revoke execute on function public\.velmere_get_owner_visible_customer_artifact_v1\(text\)[\s\S]*authenticated/i);
assert.match(current,/authorizeDelivery/); assert.match(current,/current_audit_entitlement_required/);
assert.match(json,/authorizeDelivery/); assert.match(pdf,/authorizeDelivery/);
assert.match(shield,/after-pro-cannot-read-stored-advanced/);
assert.match(shield,/after-pro-cannot-restore-stored-advanced/);
assert.match(shield,/revoked-grant-denied/); assert.match(shield,/expired-grant-denied/);
assert.equal(policy.customerContractFinalized,false);
assert.equal(policy.unknownPaidSurfaceBehavior,"FAIL_CLOSED_POLICY_UNDEFINED");
assert.equal(policy.directBrowserStorageReadAllowed,false);
console.log("C14-P14 static downgrade/report surface checks PASS");
